Developing a JSF Portlet Application
stiemannkj1/liferay-docs pull request #1
Opened 2019-05-30 15:21 UTC by codyhoag

Hey Kyle,

Can you review the *Developing a JSF Portlet Application* for accuracy? Note, this generalized article is targeted for JSF developers who are migrating their web app to work on Liferay Portal. Let me know if there are any additional things we should point out. Thanks!

2019-05-30 21:14 UTC, stiemannkj1 requested changes
@codyhoag, the article looks fantastic. It's a really brilliant idea that I think will help lots of devs and it's really clear and well written and technically accurate (especially the benefits/drawbacks of JSF section). I noticed 4 minor issues, but once those are fixed, I think this is ready to be published.

2019-05-30 21:14 UTC, stiemannkj1 commented on developer/appdev/articles/01-web-front-ends/06-jsf-portlet/01-jsf-portlet-intro.markdown
> +  such as Ajax Push.
Remove the part about Ajax push as it's unlikely to work in Liferay 7.0 and it's not really that popular anymore I think.

2019-05-30 21:14 UTC, stiemannkj1 commented on developer/appdev/articles/01-web-front-ends/06-jsf-portlet/01-jsf-portlet-intro.markdown
> +HTML document. Sticking with JavaScript and leveraging AlloyUI or some other
AlloyUI is deprecated as far as I know and should not be promoted. Check with the front-end folks to make sure.

2019-05-30 21:14 UTC, stiemannkj1 commented on developer/appdev/articles/01-web-front-ends/06-jsf-portlet/02-developing-a-jsf-portlet-application.markdown
> +    using the implicit `i18n` object provided by the Liferay Faces Util class.
~the Liferay Faces Util class~ -> Liferay Faces Util

2019-05-30 21:14 UTC, stiemannkj1 commented on developer/appdev/articles/01-web-front-ends/06-jsf-portlet/02-developing-a-jsf-portlet-application.markdown
> +    This is useful if you want to include your own CDI implementation with your
I like the text here, but it's technically required to use `-cdiannotations:` with JSF + CDI in Liferay. Devs won't be able to take advantage of Liferay's included CDI impl until we add thin-war support. So perhaps this should be reworded to reflect that it's a requirement for JSF + CDI portlets (not necessary for non-CDI, JSF portlets though).

2019-05-31 00:39 UTC, codyhoag commented
Thanks for the quick feedback, @stiemannkj1! I've incorporated your feedback and sent on for publication.

2019-05-31 00:39 UTC, closed without merging